### PR TITLE
Html

### PR DESCRIPTION
**Pull request by TedCart**

### CODE REVIEW

**Comment by wbounas** [comment]
did you `git pull --rebase origin development` before you pushed this?

there are merge conflicts

```
Conflicting files
assets/scripts/index.js
assets/scripts/ui.js```

**Comment by TedCart** [comment]
yes, i rebased several times to be sure, both the development branch and the html branch

we just need to resolve the conflicts

**Comment by TedCart** [comment]
trying again hold on

**Comment by skinnybuff** [comment]
can you rename this please:
Fix for index js require
changed events require file path to point to books/event.js

**Pull request closed without merging**
